apiVersion: v1
kind: Pod
metadata:
  name: ml-hpc-pod
spec:
  containers:
  - name: ml-hpc-container
    image: adhfmz7/ml-hpc-assignment:latest
    resources:
      limits:
        cpu: "4"
        memory: "8Gi"
        nvidia.com/gpu: 1
